/****** dim Customer table  ******/
SELECT  --[Order ID]
      --,[Order Date]
      --,[Ship Date]
	    [Customer ID]
      ,[Customer Name]
      --,[Aging]as [Shipping days]
      --,[Ship Mode]
      --,[Product Category]
      --,[Product]
      --,[ Sales ]
      --,[Quantity]
      --,[Discount]
      --,[ Profit ]
     -- ,[ Shipping Cost ]
     -- ,[Order Priority]
      ,[Segment]
      ,[City]
      ,[State]
      ,[Country]
      ,[Region]
      --,[Months]    
  FROM [sales_project].[dbo].[sales_data]