/****** Product Table ******/
SELECT  [Order ID]
	   ,[Customer ID]
	   ,[Order Date]
      ,[Ship Date]
      ,[Shiping_days]
      --,[Ship Mode]
      ,[Product Category]
      ,[Product]
      ,[ Sales ]
      ,[Quantity]
      ,[Discount]
      ,[ Profit ]
      --,[ Shipping Cost ]
      ,[Order Priority]
      --,[Customer Name]
      --,[Segment]
      --,[City]
      --,[State]
      --,[Country]
      --,[Region]
      ,[Months]
  FROM [sales_project].[dbo].[sales_data]